name: Deploy to staging

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.6

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --deployment

      - name: Deploy with Capistrano
        env:
          SSH_PRIVATE_KEY: ${{ secrets.STAGING_DEPLOY_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > deploy_key
          chmod 600 deploy_key
          bundle exec cap staging deploy
